#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmDBManagement
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_Videotheque_Waremme")]
	public partial class BDVideothequeBManagementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBDB_Film(BDB_Film instance);
    partial void UpdateBDB_Film(BDB_Film instance);
    partial void DeleteBDB_Film(BDB_Film instance);
    partial void InsertBDB_FilmGenre(BDB_FilmGenre instance);
    partial void UpdateBDB_FilmGenre(BDB_FilmGenre instance);
    partial void DeleteBDB_FilmGenre(BDB_FilmGenre instance);
    partial void InsertBDB_Genre(BDB_Genre instance);
    partial void UpdateBDB_Genre(BDB_Genre instance);
    partial void DeleteBDB_Genre(BDB_Genre instance);
    partial void InsertBDB_New(BDB_New instance);
    partial void UpdateBDB_New(BDB_New instance);
    partial void DeleteBDB_New(BDB_New instance);
    partial void InsertBDB_FilmRealisateur(BDB_FilmRealisateur instance);
    partial void UpdateBDB_FilmRealisateur(BDB_FilmRealisateur instance);
    partial void DeleteBDB_FilmRealisateur(BDB_FilmRealisateur instance);
    partial void InsertBDB_Realisateur(BDB_Realisateur instance);
    partial void UpdateBDB_Realisateur(BDB_Realisateur instance);
    partial void DeleteBDB_Realisateur(BDB_Realisateur instance);
    #endregion
		
		public BDVideothequeBManagementDataContext() : 
				base(global::FilmDBManagement.Properties.Settings.Default.BD_Videotheque_WaremmeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDVideothequeBManagementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDVideothequeBManagementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDVideothequeBManagementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDVideothequeBManagementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BDB_Film> BDB_Films
		{
			get
			{
				return this.GetTable<BDB_Film>();
			}
		}
		
		public System.Data.Linq.Table<BDB_FilmGenre> BDB_FilmGenres
		{
			get
			{
				return this.GetTable<BDB_FilmGenre>();
			}
		}
		
		public System.Data.Linq.Table<BDB_Genre> BDB_Genres
		{
			get
			{
				return this.GetTable<BDB_Genre>();
			}
		}
		
		public System.Data.Linq.Table<BDB_New> BDB_News
		{
			get
			{
				return this.GetTable<BDB_New>();
			}
		}
		
		public System.Data.Linq.Table<BDB_FilmRealisateur> BDB_FilmRealisateurs
		{
			get
			{
				return this.GetTable<BDB_FilmRealisateur>();
			}
		}
		
		public System.Data.Linq.Table<BDB_Realisateur> BDB_Realisateurs
		{
			get
			{
				return this.GetTable<BDB_Realisateur>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BDB_Film")]
	public partial class BDB_Film : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _title;
		
		private string _original_title;
		
		private int _runtime;
		
		private string _posterpath;
		
		private string _status;
		
		private EntitySet<BDB_FilmGenre> _BDB_FilmGenres;
		
		private EntitySet<BDB_FilmRealisateur> _BDB_FilmRealisateurs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void Onoriginal_titleChanging(string value);
    partial void Onoriginal_titleChanged();
    partial void OnruntimeChanging(int value);
    partial void OnruntimeChanged();
    partial void OnposterpathChanging(string value);
    partial void OnposterpathChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public BDB_Film()
		{
			this._BDB_FilmGenres = new EntitySet<BDB_FilmGenre>(new Action<BDB_FilmGenre>(this.attach_BDB_FilmGenres), new Action<BDB_FilmGenre>(this.detach_BDB_FilmGenres));
			this._BDB_FilmRealisateurs = new EntitySet<BDB_FilmRealisateur>(new Action<BDB_FilmRealisateur>(this.attach_BDB_FilmRealisateurs), new Action<BDB_FilmRealisateur>(this.detach_BDB_FilmRealisateurs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_original_title", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string original_title
		{
			get
			{
				return this._original_title;
			}
			set
			{
				if ((this._original_title != value))
				{
					this.Onoriginal_titleChanging(value);
					this.SendPropertyChanging();
					this._original_title = value;
					this.SendPropertyChanged("original_title");
					this.Onoriginal_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_runtime", DbType="Int NOT NULL")]
		public int runtime
		{
			get
			{
				return this._runtime;
			}
			set
			{
				if ((this._runtime != value))
				{
					this.OnruntimeChanging(value);
					this.SendPropertyChanging();
					this._runtime = value;
					this.SendPropertyChanged("runtime");
					this.OnruntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_posterpath", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string posterpath
		{
			get
			{
				return this._posterpath;
			}
			set
			{
				if ((this._posterpath != value))
				{
					this.OnposterpathChanging(value);
					this.SendPropertyChanging();
					this._posterpath = value;
					this.SendPropertyChanged("posterpath");
					this.OnposterpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BDB_Film_BDB_FilmGenre", Storage="_BDB_FilmGenres", ThisKey="ID", OtherKey="IDFilm")]
		public EntitySet<BDB_FilmGenre> BDB_FilmGenres
		{
			get
			{
				return this._BDB_FilmGenres;
			}
			set
			{
				this._BDB_FilmGenres.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BDB_Film_BDB_FilmRealisateur", Storage="_BDB_FilmRealisateurs", ThisKey="ID", OtherKey="IDFilm")]
		public EntitySet<BDB_FilmRealisateur> BDB_FilmRealisateurs
		{
			get
			{
				return this._BDB_FilmRealisateurs;
			}
			set
			{
				this._BDB_FilmRealisateurs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BDB_FilmGenres(BDB_FilmGenre entity)
		{
			this.SendPropertyChanging();
			entity.BDB_Film = this;
		}
		
		private void detach_BDB_FilmGenres(BDB_FilmGenre entity)
		{
			this.SendPropertyChanging();
			entity.BDB_Film = null;
		}
		
		private void attach_BDB_FilmRealisateurs(BDB_FilmRealisateur entity)
		{
			this.SendPropertyChanging();
			entity.BDB_Film = this;
		}
		
		private void detach_BDB_FilmRealisateurs(BDB_FilmRealisateur entity)
		{
			this.SendPropertyChanging();
			entity.BDB_Film = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BDB_FilmGenre")]
	public partial class BDB_FilmGenre : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDFilm;
		
		private int _IDGenre;
		
		private EntityRef<BDB_Film> _BDB_Film;
		
		private EntityRef<BDB_Genre> _BDB_Genre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDFilmChanging(int value);
    partial void OnIDFilmChanged();
    partial void OnIDGenreChanging(int value);
    partial void OnIDGenreChanged();
    #endregion
		
		public BDB_FilmGenre()
		{
			this._BDB_Film = default(EntityRef<BDB_Film>);
			this._BDB_Genre = default(EntityRef<BDB_Genre>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDFilm", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDFilm
		{
			get
			{
				return this._IDFilm;
			}
			set
			{
				if ((this._IDFilm != value))
				{
					if (this._BDB_Film.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDFilmChanging(value);
					this.SendPropertyChanging();
					this._IDFilm = value;
					this.SendPropertyChanged("IDFilm");
					this.OnIDFilmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDGenre", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDGenre
		{
			get
			{
				return this._IDGenre;
			}
			set
			{
				if ((this._IDGenre != value))
				{
					if (this._BDB_Genre.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDGenreChanging(value);
					this.SendPropertyChanging();
					this._IDGenre = value;
					this.SendPropertyChanged("IDGenre");
					this.OnIDGenreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BDB_Film_BDB_FilmGenre", Storage="_BDB_Film", ThisKey="IDFilm", OtherKey="ID", IsForeignKey=true)]
		public BDB_Film BDB_Film
		{
			get
			{
				return this._BDB_Film.Entity;
			}
			set
			{
				BDB_Film previousValue = this._BDB_Film.Entity;
				if (((previousValue != value) 
							|| (this._BDB_Film.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BDB_Film.Entity = null;
						previousValue.BDB_FilmGenres.Remove(this);
					}
					this._BDB_Film.Entity = value;
					if ((value != null))
					{
						value.BDB_FilmGenres.Add(this);
						this._IDFilm = value.ID;
					}
					else
					{
						this._IDFilm = default(int);
					}
					this.SendPropertyChanged("BDB_Film");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BDB_Genre_BDB_FilmGenre", Storage="_BDB_Genre", ThisKey="IDGenre", OtherKey="Id", IsForeignKey=true)]
		public BDB_Genre BDB_Genre
		{
			get
			{
				return this._BDB_Genre.Entity;
			}
			set
			{
				BDB_Genre previousValue = this._BDB_Genre.Entity;
				if (((previousValue != value) 
							|| (this._BDB_Genre.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BDB_Genre.Entity = null;
						previousValue.BDB_FilmGenres.Remove(this);
					}
					this._BDB_Genre.Entity = value;
					if ((value != null))
					{
						value.BDB_FilmGenres.Add(this);
						this._IDGenre = value.Id;
					}
					else
					{
						this._IDGenre = default(int);
					}
					this.SendPropertyChanged("BDB_Genre");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BDB_Genre")]
	public partial class BDB_Genre : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
		private EntitySet<BDB_FilmGenre> _BDB_FilmGenres;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public BDB_Genre()
		{
			this._BDB_FilmGenres = new EntitySet<BDB_FilmGenre>(new Action<BDB_FilmGenre>(this.attach_BDB_FilmGenres), new Action<BDB_FilmGenre>(this.detach_BDB_FilmGenres));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BDB_Genre_BDB_FilmGenre", Storage="_BDB_FilmGenres", ThisKey="Id", OtherKey="IDGenre")]
		public EntitySet<BDB_FilmGenre> BDB_FilmGenres
		{
			get
			{
				return this._BDB_FilmGenres;
			}
			set
			{
				this._BDB_FilmGenres.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BDB_FilmGenres(BDB_FilmGenre entity)
		{
			this.SendPropertyChanging();
			entity.BDB_Genre = this;
		}
		
		private void detach_BDB_FilmGenres(BDB_FilmGenre entity)
		{
			this.SendPropertyChanging();
			entity.BDB_Genre = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BDB_News")]
	public partial class BDB_New : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Titre;
		
		private string _Contenu;
		
		private System.DateTime _CreateDate;
		
		private System.Nullable<System.DateTime> _ModifDate;
		
		private System.Data.Linq.Binary _Image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTitreChanging(string value);
    partial void OnTitreChanged();
    partial void OnContenuChanging(string value);
    partial void OnContenuChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnModifDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifDateChanged();
    partial void OnImageChanging(System.Data.Linq.Binary value);
    partial void OnImageChanged();
    #endregion
		
		public BDB_New()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Titre
		{
			get
			{
				return this._Titre;
			}
			set
			{
				if ((this._Titre != value))
				{
					this.OnTitreChanging(value);
					this.SendPropertyChanging();
					this._Titre = value;
					this.SendPropertyChanged("Titre");
					this.OnTitreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contenu", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Contenu
		{
			get
			{
				return this._Contenu;
			}
			set
			{
				if ((this._Contenu != value))
				{
					this.OnContenuChanging(value);
					this.SendPropertyChanging();
					this._Contenu = value;
					this.SendPropertyChanged("Contenu");
					this.OnContenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifDate
		{
			get
			{
				return this._ModifDate;
			}
			set
			{
				if ((this._ModifDate != value))
				{
					this.OnModifDateChanging(value);
					this.SendPropertyChanging();
					this._ModifDate = value;
					this.SendPropertyChanged("ModifDate");
					this.OnModifDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BDB_FilmRealisateur")]
	public partial class BDB_FilmRealisateur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDFilm;
		
		private int _IDReal;
		
		private EntityRef<BDB_Film> _BDB_Film;
		
		private EntityRef<BDB_Realisateur> _BDB_Realisateur;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDFilmChanging(int value);
    partial void OnIDFilmChanged();
    partial void OnIDRealChanging(int value);
    partial void OnIDRealChanged();
    #endregion
		
		public BDB_FilmRealisateur()
		{
			this._BDB_Film = default(EntityRef<BDB_Film>);
			this._BDB_Realisateur = default(EntityRef<BDB_Realisateur>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDFilm", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDFilm
		{
			get
			{
				return this._IDFilm;
			}
			set
			{
				if ((this._IDFilm != value))
				{
					if (this._BDB_Film.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDFilmChanging(value);
					this.SendPropertyChanging();
					this._IDFilm = value;
					this.SendPropertyChanged("IDFilm");
					this.OnIDFilmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDReal", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDReal
		{
			get
			{
				return this._IDReal;
			}
			set
			{
				if ((this._IDReal != value))
				{
					if (this._BDB_Realisateur.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDRealChanging(value);
					this.SendPropertyChanging();
					this._IDReal = value;
					this.SendPropertyChanged("IDReal");
					this.OnIDRealChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BDB_Film_BDB_FilmRealisateur", Storage="_BDB_Film", ThisKey="IDFilm", OtherKey="ID", IsForeignKey=true)]
		public BDB_Film BDB_Film
		{
			get
			{
				return this._BDB_Film.Entity;
			}
			set
			{
				BDB_Film previousValue = this._BDB_Film.Entity;
				if (((previousValue != value) 
							|| (this._BDB_Film.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BDB_Film.Entity = null;
						previousValue.BDB_FilmRealisateurs.Remove(this);
					}
					this._BDB_Film.Entity = value;
					if ((value != null))
					{
						value.BDB_FilmRealisateurs.Add(this);
						this._IDFilm = value.ID;
					}
					else
					{
						this._IDFilm = default(int);
					}
					this.SendPropertyChanged("BDB_Film");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BDB_Realisateur_BDB_FilmRealisateur", Storage="_BDB_Realisateur", ThisKey="IDReal", OtherKey="Id", IsForeignKey=true)]
		public BDB_Realisateur BDB_Realisateur
		{
			get
			{
				return this._BDB_Realisateur.Entity;
			}
			set
			{
				BDB_Realisateur previousValue = this._BDB_Realisateur.Entity;
				if (((previousValue != value) 
							|| (this._BDB_Realisateur.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BDB_Realisateur.Entity = null;
						previousValue.BDB_FilmRealisateurs.Remove(this);
					}
					this._BDB_Realisateur.Entity = value;
					if ((value != null))
					{
						value.BDB_FilmRealisateurs.Add(this);
						this._IDReal = value.Id;
					}
					else
					{
						this._IDReal = default(int);
					}
					this.SendPropertyChanged("BDB_Realisateur");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BDB_Realisateur")]
	public partial class BDB_Realisateur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _name;
		
		private EntitySet<BDB_FilmRealisateur> _BDB_FilmRealisateurs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
		
		public BDB_Realisateur()
		{
			this._BDB_FilmRealisateurs = new EntitySet<BDB_FilmRealisateur>(new Action<BDB_FilmRealisateur>(this.attach_BDB_FilmRealisateurs), new Action<BDB_FilmRealisateur>(this.detach_BDB_FilmRealisateurs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BDB_Realisateur_BDB_FilmRealisateur", Storage="_BDB_FilmRealisateurs", ThisKey="Id", OtherKey="IDReal")]
		public EntitySet<BDB_FilmRealisateur> BDB_FilmRealisateurs
		{
			get
			{
				return this._BDB_FilmRealisateurs;
			}
			set
			{
				this._BDB_FilmRealisateurs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BDB_FilmRealisateurs(BDB_FilmRealisateur entity)
		{
			this.SendPropertyChanging();
			entity.BDB_Realisateur = this;
		}
		
		private void detach_BDB_FilmRealisateurs(BDB_FilmRealisateur entity)
		{
			this.SendPropertyChanging();
			entity.BDB_Realisateur = null;
		}
	}
}
#pragma warning restore 1591
