//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALBDVideo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-IQTHKHPT\\SQLEXPRESS;Initial Catalog=BD_Videotheque_Liege;Integ" +
            "rated Security=True;Pooling=False")]
        public string BD_Videotheque_LiegeConnectionString {
            get {
                return ((string)(this["BD_Videotheque_LiegeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-IQTHKHPT\\SQLEXPRESS;Initial Catalog=BD_Videotheque_Waremme;Int" +
            "egrated Security=True;Pooling=False")]
        public string BD_Videotheque_WaremmeConnectionString {
            get {
                return ((string)(this["BD_Videotheque_WaremmeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LEOPARDGK\\SQLEXPRESS;Initial Catalog=BD_Videotheque_Liege;Integrated " +
            "Security=True;Encrypt=False;TrustServerCertificate=True")]
        public string BD_Videotheque_LiegeConnectionString1 {
            get {
                return ((string)(this["BD_Videotheque_LiegeConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-IQTHKHPT\\SQLEXPRESS;Initial Catalog=BD_Videotheque_Liege;Integ" +
            "rated Security=True")]
        public string BD_Videotheque_LiegeConnectionString2 {
            get {
                return ((string)(this["BD_Videotheque_LiegeConnectionString2"]));
            }
        }
    }
}
